export enum MailType {
  ORDER = 1,
  REFUND = 2,
  CREDENTIALS = 3,
  QUOTATIONS = 4,
  COMPLAINT = 5,
  RESCHEDULE = 6,
  CSI = 7,
  REPLACE_TUKANG_FROM_VENDOR = 8,
  REPLACE_TUKANG_FROM_TUKANG = 9,
  QUOTATION_PAYMENT = 10,
}
