export enum InvoiceStatus {
  PENGECEKAN_INVOICE = 1,
  INVOICE_DISETUJUI = 2,
  INVOICE_DITOLAK = 3,
  MENUNGGU_DOKUMEN_TAGIHAN = 4,
  INVOICE_DIBERIKAN_KEPADA_FINANCE = 5,
  INVOICE_SUDAH_DIBAYARKAN = 6,
  DOKUMEN_DITOLAK = 7,
}
