import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
export async function CitySeed() {
  const cities = [
    'Denpasar',
    'Bandung',
    'Batu',
    'Bekasi',
    'Blitar',
    'Cianjur',
    'Cilegon',
    'Cimahi',
    'Cirebon',
    'Depok',
    'Jakarta',
    'Madiun',
    'Magelang',
    'Malang',
    'Mojokerto',
    'Pasuruan',
    'Pekalongan',
    'Probolinggo',
    'Salatiga',
    'Semarang',
    'South Tangerang',
    'Sukabumi',
    'Surabaya',
    'Surakarta',
    'Tasikmalaya',
    'Tangerang',
    'Tegal',
    'Yogyakarta',
    'Kediri',
    'Serang',
    'Purwokerto',
    'Balikpapan',
    'Banjarbaru',
    'Banjarmasin',
    'Bontang',
    'Palangkaraya',
    'Pontianak',
    'Samarinda',
    'Singkawang',
    'Tarakan',
    'Tenggarong',
    'Ambon',
    'Tual',
    'Ternate',
    'Tidore',
    'Bima',
    'Mataram',
    'Kupang',
    'Jayapura',
    'Merauke',
    'Kota Sorong',
    'Manokwari',
    'Bau-Bau',
    'Bitung',
    'Gorontalo',
    'Kendari',
    'Makassar',
    'Manado',
    'Palu',
    'Pare-Pare',
    'Palopo',
    'Tomohon',
    'Banda Aceh',
    'Bandar Lampung',
    'Batam',
    'Bengkulu',
    'Blangkejeren',
    'Binjai',
    'Bireuen',
    'Bukittinggi',
    'Dumai',
    'Jambi',
    'Langsa',
    'Lhokseumawe',
    'Lubuklinggau',
    'Meulaboh',
    'Medan',
    'Metro',
    'Padang',
    'Padang Panjang',
    'Padang Sidempuan',
    'Pagar Alam',
    'Palembang',
    'Pangkal Pinang',
    'Pariaman',
    'Payakumbuh',
    'Pekanbaru',
    'Pematang Siantar',
    'Prabumulih',
    'Sigli',
    'Redelong (Simpang Tiga Redelong)',
    'Sabang',
    'Sawah Lunto',
    'Sibolga',
    'Singkil',
    'Solok',
    'Takengon',
    'Tapaktuan',
    'Tanjung Balai',
    'Tanjung Pinang',
    'Tebing Tinggi',
  ];

  await prisma.city.createMany({
    data: cities.map((city) => ({ city_name: city })),
  });
}
